이 노트북의 코드에 대한 설명은 [다중 평가 지표: cross_validate()](https://tensorflow.blog/2018/03/13/%EB%8B%A4%EC%A4%91-%ED%8F%89%EA%B0%80-%EC%A7%80%ED%91%9C-cross_validate/) 글을 참고하세요.

In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split, cross_val_score

In [2]:
digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(
    digits.data, digits.target == 9, random_state=42)

In [3]:
from sklearn.svm import SVC

In [4]:
cross_val_score(SVC(gamma='auto'), X_train, y_train, cv=3)

array([0.90200445, 0.90200445, 0.90200445])

In [5]:
cross_val_score(SVC(gamma='auto'), X_train, y_train, scoring='accuracy', cv=3)

array([0.90200445, 0.90200445, 0.90200445])

In [6]:
from sklearn.model_selection import cross_validate

In [7]:
cross_validate(SVC(gamma='auto'), X_train, y_train, 
               scoring=['accuracy', 'roc_auc'], 
               return_train_score=True, cv=3)

{'fit_time': array([0.06283069, 0.05705523, 0.06088758]),
 'score_time': array([0.06714225, 0.06660008, 0.06989026]),
 'test_accuracy': array([0.90200445, 0.90200445, 0.90200445]),
 'train_accuracy': array([1., 1., 1.]),
 'test_roc_auc': array([0.99657688, 0.99814815, 0.99943883]),
 'train_roc_auc': array([1., 1., 1.])}

In [8]:
cross_validate(SVC(gamma='auto'), X_train, y_train, 
               scoring=['accuracy'], cv=3,
               return_train_score=False)['test_accuracy']

array([0.90200445, 0.90200445, 0.90200445])

In [9]:
cross_validate(SVC(gamma='auto'), X_train, y_train, 
               scoring={'acc':'accuracy', 'ra':'roc_auc'}, 
               return_train_score=False, cv=3)

{'fit_time': array([0.06284761, 0.05526924, 0.05580401]),
 'score_time': array([0.06862092, 0.06707287, 0.06863403]),
 'test_acc': array([0.90200445, 0.90200445, 0.90200445]),
 'test_ra': array([0.99657688, 0.99814815, 0.99943883])}

In [10]:
from sklearn.model_selection import GridSearchCV

In [11]:
param_grid = {'gamma': [0.0001, 0.01, 0.1, 1, 10]}

In [12]:
grid = GridSearchCV(SVC(), param_grid=param_grid, 
                    scoring=['accuracy'], refit='accuracy',
                    return_train_score=True, cv=3)
grid.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'gamma': [0.0001, 0.01, 0.1, 1, 10]}, refit='accuracy',
             return_train_score=True, scoring=['accuracy'])

In [13]:
grid.best_params_

{'gamma': 0.0001}

In [14]:
grid.best_score_

0.9651076466221232

In [15]:
np.transpose(pd.DataFrame(grid.cv_results_))

0                1               2  \
mean_fit_time                   0.013797         0.056774        0.060325   
std_fit_time                    0.002508         0.001482         0.00114   
mean_score_time                 0.007289         0.035897         0.03611   
std_score_time                   0.00047         0.001759        0.001099   
param_gamma                       0.0001             0.01             0.1   
params                 {'gamma': 0.0001}  {'gamma': 0.01}  {'gamma': 0.1}   
split0_test_accuracy            0.966592         0.902004        0.902004   
split1_test_accuracy             0.96882         0.902004        0.902004   
split2_test_accuracy            0.959911         0.902004        0.902004   
mean_test_accuracy              0.965108         0.902004        0.902004   
std_test_accuracy               0.003785              0.0             0.0   
rank_test_accuracy                     1                2               2   
split0_train_accuracy           0.975501              1.0             1.0   
split1_train_accuracy           0.962138              1.0             1.0   
split2_train_accuracy           0.974388              1.0             1.0   
mean_train_accuracy             0.970676              1.0             1.0   
std_train_accuracy              0.006054              0.0             0.0   

                                  3              4  
mean_fit_time              0.052677       0.050805  
std_fit_time               0.005908       0.006054  
mean_score_time            0.036614        0.03795  
std_score_time             0.004151       0.006425  
param_gamma                       1             10  
params                 {'gamma': 1}  {'gamma': 10}  
split0_test_accuracy       0.902004       0.902004  
split1_test_accuracy       0.902004       0.902004  
split2_test_accuracy       0.902004       0.902004  
mean_test_accuracy         0.902004       0.902004  
std_test_accuracy               0.0            0.0  
rank_test_accuracy                2              2  
split0_train_accuracy           1.0            1.0  
split1_train_accuracy           1.0            1.0  
split2_train_accuracy           1.0            1.0  
mean_train_accuracy             1.0            1.0  
std_train_accuracy              0.0            0.0

In [16]:
grid = GridSearchCV(SVC(), param_grid=param_grid, 
                    scoring={'acc':'accuracy', 'ra':'roc_auc'}, refit='ra',
                    return_train_score=True, cv=3)
grid.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'gamma': [0.0001, 0.01, 0.1, 1, 10]}, refit='ra',
             return_train_score=True,
             scoring={'acc': 'accuracy', 'ra': 'roc_auc'})

In [17]:
grid.best_params_

{'gamma': 0.01}

In [18]:
grid.best_score_

0.9983352038907594

In [19]:
np.transpose(pd.DataFrame(grid.cv_results_))

0                1               2  \
mean_fit_time              0.013306         0.054456         0.05906   
std_fit_time                0.00266         0.000214        0.002891   
mean_score_time            0.015617         0.069796        0.073554   
std_score_time              0.00071         0.003148        0.003971   
param_gamma                  0.0001             0.01             0.1   
params            {'gamma': 0.0001}  {'gamma': 0.01}  {'gamma': 0.1}   
split0_test_acc            0.966592         0.902004        0.902004   
split1_test_acc             0.96882         0.902004        0.902004   
split2_test_acc            0.959911         0.902004        0.902004   
mean_test_acc              0.965108         0.902004        0.902004   
std_test_acc               0.003785              0.0             0.0   
rank_test_acc                     1                2               2   
split0_train_acc           0.975501              1.0             1.0   
split1_train_acc           0.962138              1.0             1.0   
split2_train_acc           0.974388              1.0             1.0   
mean_train_acc             0.970676              1.0             1.0   
std_train_acc              0.006054              0.0             0.0   
split0_test_ra              0.98367         0.997419        0.934007   
split1_test_ra             0.987149         0.998148        0.912458   
split2_test_ra             0.994388         0.999439        0.910494   
mean_test_ra               0.988403         0.998335        0.918986   
std_test_ra                0.004465         0.000835        0.010651   
rank_test_ra                      2                1               3   
split0_train_ra            0.992017              1.0             1.0   
split1_train_ra            0.994935              1.0             1.0   
split2_train_ra             0.98945              1.0             1.0   
mean_train_ra              0.992134              1.0             1.0   
std_train_ra               0.002241              0.0             0.0   

                             3              4  
mean_fit_time         0.045849       0.045366  
std_fit_time          0.000387       0.000173  
mean_score_time       0.070676       0.073917  
std_score_time        0.000227       0.000649  
param_gamma                  1             10  
params            {'gamma': 1}  {'gamma': 10}  
split0_test_acc       0.902004       0.902004  
split1_test_acc       0.902004       0.902004  
split2_test_acc       0.902004       0.902004  
mean_test_acc         0.902004       0.902004  
std_test_acc               0.0            0.0  
rank_test_acc                2              2  
split0_train_acc           1.0            1.0  
split1_train_acc           1.0            1.0  
split2_train_acc           1.0            1.0  
mean_train_acc             1.0            1.0  
std_train_acc              0.0            0.0  
split0_test_ra             0.5            0.5  
split1_test_ra             0.5            0.5  
split2_test_ra             0.5            0.5  
mean_test_ra               0.5            0.5  
std_test_ra                0.0            0.0  
rank_test_ra                 4              4  
split0_train_ra            1.0            1.0  
split1_train_ra            1.0            1.0  
split2_train_ra            1.0            1.0  
mean_train_ra              1.0            1.0  
std_train_ra               0.0            0.0

In [20]:
grid.best_estimator_

SVC(gamma=0.01)